### ISSUE TITLE
ネストされたRoutedContentでpop時にクラッシュする

### ISSUE THREAD

**Issue by tkhs-dev** [tkhs-dev/HandaiManager#1]
例: ホームから設定を開いて戻るボタンで戻った時(RootScreenとHomeScreenでネストされている)
```
java.lang.IllegalStateException: Another supplier is already registered with the key: HomeScreenPage
                                                                                                    	at com.arkivanov.essenty.statekeeper.DefaultStateKeeperDispatcher.register(DefaultStateKeeperDispatcher.kt:44)
                                                                                                    	at com.arkivanov.decompose.router.children.ChildrenFactoryKt.children(ChildrenFactory.kt:93)
                                                                                                    	at com.arkivanov.decompose.router.children.ChildrenFactoryKt.children$default(ChildrenFactory.kt:61)
                                                                                                    	at com.arkivanov.decompose.router.stack.ChildStackFactoryKt.childStack(ChildStackFactory.kt:91)
                                                                                                    	at com.arkivanov.decompose.router.stack.ChildStackFactoryKt.childStack(ChildStackFactory.kt:40)
                                                                                                    	at com.arkivanov.decompose.router.stack.ChildStackFactoryKt.childStack$default(ChildStackFactory.kt:31)
                                                                                                    	at io.github.xxfast.decompose.NavigatorKt.rememberChildStack(Navigator.kt:36)
                                                                                                    	at io.github.xxfast.decompose.router.RouterKt.rememberRouter(Router.kt:58)
                                                                                                    	at ui.screen.home.HomeScreenKt.HomeScreen(HomeScreen.kt:51)
                                                                                                    	at ui.RootScreenKt$RootScreen$1.invoke(RootScreen.kt:28)
                                                                                                    	at ui.RootScreenKt$RootScreen$1.invoke(RootScreen.kt:23)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:117)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at io.github.xxfast.decompose.router.content.RoutedContentKt$RoutedContent$1$1$1.invoke(RoutedContent.kt:36)
                                                                                                    	at io.github.xxfast.decompose.router.content.RoutedContentKt$RoutedContent$1$1$1.invoke(RoutedContent.kt:35)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                                                                                                    	at io.github.xxfast.decompose.router.content.RoutedContentKt$RoutedContent$1$1.invoke(RoutedContent.kt:35)
                                                                                                    	at io.github.xxfast.decompose.router.content.RoutedContentKt$RoutedContent$1$1.invoke(RoutedContent.kt:34)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:117)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at com.arkivanov.decompose.extensions.compose.jetbrains.stack.ChildrenKt$Children$1$1.invoke(Children.kt:31)
                                                                                                    	at com.arkivanov.decompose.extensions.compose.jetbrains.stack.ChildrenKt$Children$1$1.invoke(Children.kt:30)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                                                                                                    	at androidx.compose.runtime.saveable.SaveableStateHolderImpl.SaveableStateProvider(SaveableStateHolder.kt:84)
                                                                                                    	at com.arkivanov.decompose.extensions.compose.jetbrains.stack.ChildrenKt$Children$1.invoke(Children.kt:30)
                                                                                                    	at com.arkivanov.decompose.extensions.compose.jetbrains.stack.ChildrenKt$Children$1.invoke(Children.kt:29)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:117)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at com.arkivanov.decompose.extensions.compose.jetbrains.stack.animation.SimpleStackAnimation$Child$1.invoke(SimpleStackAnimation.kt:27)
                                                                                                    	at com.arkivanov.decompose.extensions.compose.jetbrains.stack.animation.SimpleStackAnimation$Child$1.invoke(SimpleStackAnimation.kt:25)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:117)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at com.arkivanov.decompose.extensions.compose.jetbrains.stack.animation.FadeKt$fade$1.invoke(Fade.kt:18)
                                                                                                    	at com.arkivanov.decompose.extensions.compose.jetbrains.stack.animation.FadeKt$fade$1.invoke(Fade.kt:17)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:154)
2023-09-22 13:36:14.451 26208-26208 AndroidRuntime          dev...s.handaimanager.HandaiManager  E  	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at com.arkivanov.decompose.extensions.compose.jetbrains.stack.animation.DefaultStackAnimator.invoke(DefaultStackAnimator.kt:45)
                                                                                                    	at com.arkivanov.decompose.extensions.compose.jetbrains.stack.animation.SimpleStackAnimation.Child(SimpleStackAnimation.kt:21)
                                                                                                    	at com.arkivanov.decompose.extensions.compose.jetbrains.stack.animation.AbstractStackAnimation.invoke(AbstractStackAnimation.kt:40)
                                                                                                    	at com.arkivanov.decompose.extensions.compose.jetbrains.stack.ChildrenKt.Children(Children.kt:29)
                                                                                                    	at io.github.xxfast.decompose.router.content.RoutedContentKt$RoutedContent$1.invoke(RoutedContent.kt:30)
                                                                                                    	at io.github.xxfast.decompose.router.content.RoutedContentKt$RoutedContent$1.invoke(RoutedContent.kt:29)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:169)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2468)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2737)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3352)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:3303)
                                                                                                    	at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:781)
                                                                                                    	at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:1097)
                                                                                                    	at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:124)
                                                                                                    	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:569)
                                                                                                    	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:537)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:41)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:979)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:790)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:718)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:967)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:808)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:101)
                                                                                                    	at android.os.Looper.loop(Looper.java:166)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7523)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```
[参考](https://stackoverflow.com/questions/77149045/another-supplier-is-already-registered-with-the-key-defaultchildstack-while-usi)

**Comment by tkhs-dev** [comment]
エラーは出なくなったがネストされたRouterの挙動がおかしい
Decompose-routerではネストが許されない可能性が高い

**Comment by arkivanov** [comment]
The latest version of Decompose-Router now supports nested navigation. There was a bug in the library, which is now fixed.

**Comment by tkhs-dev** [comment]
Thank you for letting me know. I'll give the latest version a try.
